- avalon/tools/projectmanager/widget.py
hiearchy in asset model is creating right now
> hiearchy in asset model is creating right now

- avalon/pipeline.py
- dyn_env seems to take place instead of app_environment
> removed forgotten lines

- avalon/maya/pipeline.py
- avalon/nuke/pipeline.py
- avalon/tools/libraryloader/__init__.py
- avalon/tools/libraryloader/__main__.py
- avalon/tools/libraryloader/app.py
- avalon/tools/libraryloader/db_connection.py
- avalon/tools/libraryloader/delegates.py
- avalon/tools/libraryloader/io_nonsingleton.py
- avalon/tools/libraryloader/lib.py
- avalon/tools/libraryloader/models/__init__.py
- avalon/tools/libraryloader/models/model_asset.py
- avalon/tools/libraryloader/models/model_filter_exact_match.py
- avalon/tools/libraryloader/models/model_filter_families.py
- avalon/tools/libraryloader/models/model_filter_recursive_sort.py
- avalon/tools/libraryloader/models/model_node.py
- avalon/tools/libraryloader/models/model_projects.py
- avalon/tools/libraryloader/models/model_subsets.py
- avalon/tools/libraryloader/models/model_tasks.py
- avalon/tools/libraryloader/models/model_tree.py
- avalon/tools/libraryloader/models/view_asset.py
- avalon/tools/libraryloader/models/view_deselect_tree.py
- avalon/tools/libraryloader/widgets/__init__.py
- avalon/tools/libraryloader/widgets/widget_asset.py
- avalon/tools/libraryloader/widgets/widget_choose_project.py
- avalon/tools/libraryloader/widgets/widget_family_list.py
- avalon/tools/libraryloader/widgets/widget_project.py
- avalon/tools/libraryloader/widgets/widget_silo_tab.py
- avalon/tools/libraryloader/widgets/widget_subset.py
- avalon/tools/libraryloader/widgets/widget_version.py
Library loader GUI is working without huge issues but need more cleanups. On API and IO ussage in first place
> Library loader GUI is working without huge issues

- avalon/pipeline.py
- avalon/tools/workfiles/app.py
filling data changed so they match default template
> filling data changed so they match default template

- avalon/pipeline.py
- avalon/tools/workfiles/app.py
Reverts pypeclub/avalon-core#24
> Revert "filling data changed so they match default template"

- avalon/pipeline.py
- avalon/tools/workfiles/app.py
Reverts pypeclub/avalon-core#25
> Revert "Revert "filling data changed so they match default template""

- avalon/tools/workfiles/app.py
- WorkFile tool finds the higher version file in script folder
> WorkFiles tool finds the higher version file in script folder

- avalon/tools/creator/app.py
- creator select family based on task name and presets
> creator select family based on task name and presets

- avalon/tools/creator/app.py
- added config file existence check
> added config file existence check

- avalon/nuke/__init__.py
- avalon/nuke/lib.py
- avalon/nuke/pipeline.py
- also fixing ls_img_sequence with clique
> feat(nuke): improving way avalon data are imprinted into nodes

- avalon/pipeline.py
please do not merge until we agree it is right time
> Little Fixes 

- avalon/tools/delegates.py
perhaps python 27 vs python 3 incompatibility of types
> fix: delegates war getting long instead of int

- avalon/nuke/lib.py
- avalon/tools/creator/app.py
adding it in-between family and subset
> feat(global): adding task to subset name

- avalon/nuke/lib.py
- avalon/nuke/pipeline.py
- avalon/pipeline.py
User:
- user can Create backdrop node and publish
- user can Load published backdrop node as precomp node with all inputs and output
‌
Depended PR:
https://bitbucket.org/pypeclub/pype/pull-requests/381/publishing-workflow-for-backdrop-nodes/diff
> Publishing workflow for backdrop nodes

- avalon/nuke/lib.py
Instead of using too much code it has been refactored the way it is using build in function from nukescripts
> feat(nuke): improvements of reset selection method

- avalon/tools/libraryloader/app.py
Refresh button caused crash of application
- fix library loader refresh button
> fix library loader refresh button

- avalon/tools/creator/app.py
> fix: not to capitalize subset name

- avalon/tools/models.py
- avalon/tools/workfiles/app.py
- avalon/tools/workfiles/model.py
- Implemented that workfile also shows `modification` data next to workfile name
- for this purpose must be replaced QListWidget wth QTreeView and adding a model for it
- more columns may be add in the future
> [PYPE-603] #close show date workfile

- avalon/tools/libraryloader/app.py
- avalon/tools/loader/app.py
Issue:
- on deselection of subset is thumbnail set to default
Solved with:
- on deselection of subsets is thumbnail set to asset's thumbnail
> feature deselect subset thumbnail

- avalon/nuke/lib.py
- adding multiple exception on knob value assignment
> PYPE-774 create write better exception knob create 

- avalon/tools/loader/delegates.py
- avalon/tools/models.py
added Qt4 Loader compatibility
> Qt4 compatibility

- avalon/tools/workfiles/app.py
This relates to #136 where we want to disable the "Save As" button.
> Toggle "Save As" button in Workfiles.

- avalon/pipeline.py
- avalon/schema/asset-3.0.json
- avalon/schema/session-2.0.json
- avalon/tools/lib.py
- avalon/tools/loader/app.py
- avalon/tools/loader/model.py
- avalon/tools/models.py
- avalon/tools/projectmanager/app.py
- avalon/tools/projectmanager/dialogs.py
- avalon/tools/projectmanager/lib.py
- avalon/tools/widgets.py
- avalon/tools/workfiles/app.py
Update latest changes in getavalon's core.
> Update upstream changes

- avalon/blender/pipeline.py
Related to pull request [#328](https://github.com/pypeclub/pype/pull/328).
> Supporting double digits namespace names

- avalon/pipeline.py
Generators always return as true.
> Generators > tuples

- avalon/style/style.qss
- avalon/tools/libraryloader/app.py
- avalon/tools/libraryloader/models.py
- avalon/tools/libraryloader/widgets.py
- avalon/tools/models.py
- avalon/tools/widgets.py
- added few specific styles
- it is possible to pass dbcon to asset widget (also removed duplicated code in library loader)
|---|---|
|pype|https://github.com/pypeclub/pype/pull/443|
|pype-config|https://github.com/pypeclub/pype-config/pull/75|
> Implementation of non QML launcher

- avalon/pipeline.py
https://github.com/pypeclub/pype/pull/459
> adding celaction to accepted extensions

- avalon/maya/pipeline.py
**What's changed?**
Added menu item for Look Manager to Pype menu
Resolves: pypeclub/pype#292
> Added mayalookassigner to Pype menu in Maya

- avalon/tools/libraryloader/widgets.py
- Library loader has also ability to show Options dialog for loaders
> Loader options in library loader

- avalon/tools/sceneinventory/app.py
Resolves https://github.com/pypeclub/pype/issues/423
> Fix scene inventory switching.

- avalon/inventory.py
- avalon/schema/config-1.1.json
- avalon/schema/inventory-1.1.json
- avalon/schema/project-2.1.json
- avalon/tests/test_inventory.py
- avalon/tools/models.py
Modifications based on change of tasks from [] to dictionary.
Requires:
pype-config:pypeclub/pype-config#81
pype:pypeclub/pype#572
> #180 - Changed tasks to dictionaries

- avalon/harmony/README.md
- avalon/harmony/TB_sceneOpened.js
- avalon/harmony/__init__.py
- avalon/harmony/lib.py
- avalon/harmony/pipeline.py
- avalon/harmony/server.py
- avalon/harmony/workio.py
- avalon/toonboom/lib.py
**UUID** prefixed function were incompatible with [ECMA](https://www.ecma-international.org/publications/standards/Ecma-262.htm). Dashes were replaced with underscores and prefixed with letter `f`.
There was also bug with locking from previous fix.
Including minor changes in better server debug output
🏴 **Relates to:** pypeclub/pype#609
|---|
> Harmony: function signature

- avalon/pipeline.py
dependent PR:
https://github.com/pypeclub/pype/pull/617
> Renaming nukestudio host folder to hiero

- avalon/photoshop/pipeline.py
Fixed update to immutable object
Closes: pypeclub/pype#650
> #650 - Fix Loader fails in Photoshop

- avalon/tvpaint/communication_server.py
- tvpaint files copy requires admin permissions but admin may not have access to source folder
- tvpaint files are copied to temp folder first and then copied with admin permissions to tvpain installation
> TVPaint plugins are copied through temp folder

- avalon/tools/widgets.py
- avalon/tvpaint/communication_server.py
- TVPaint still used `lib.refresh_family_config_cache()` and `lib.refresh_group_config_cache()`
- AssetWidget keeps selection but not current index
- removed these functions
- fixed reraise exception from main thread
- current index is kept with selection in asset widget
> TVPaint forgotten lines from tool.lib

- avalon/api.py
- avalon/pipeline.py
- avalon/tools/creator/app.py
- avalon/tools/creator/widgets.py
- it is possible to pass Create klass to `create` function so no more family based processing
- added new exception `CreatorError` for known creator errors
- creator now have message box showing errors happened during creation
- message box will show only message if `CreatorError` happened else will show whole traceback
> create expect Create class instead of family

- avalon/vendor/qtawesome/__init__.py
- avalon/vendor/qtawesome/iconic_font.py
Reverts pypeclub/avalon-core#244
> Revert "Awesome font reload fix"

- avalon/tools/workfiles/app.py
- workfile tool has extensions combobox on `Save As`
> Workfile tool allow to choose extension

- avalon/lib.py
- added import termplate `"{0}.hosts.{1}.api"` where to look for host implementation
|---|---|
|pype|https://github.com/pypeclub/pype/pull/816|
> Self contained tvpaint

- avalon/photoshop/lib.py
dependent to: https://github.com/pypeclub/pype/pull/894
> photoshop launch with template

- avalon/pipeline.py
- avalon/schema.py
- avalon/tools/delegates.py
- avalon/tools/loader/model.py
- avalon/tools/sceneinventory/app.py
- fix few issue connected to master version implementation in avalon-core
|:black_flag:|Pype 2.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/264|
> Master versions fix

- avalon/tools/sceneinventory/app.py
- after PR https://github.com/pypeclub/avalon-core/pull/130 is asset switcher broken and does not have all features as had before
- this PR fix the missing features validation issues, filling issues and make switcher loading little bit faster
- logic was separated by states of selection in combobox to understand the logic inside easier
- this caused that methods are quite bigger
Resolves: https://github.com/pypeclub/pype/issues/423
> Asset switch fix

- avalon/photoshop/lib.py
Better escaping of \ in workfile path.
|:black_flag: |Pype 3.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/273
> Photoshop safer loading workfile

- avalon/harmony/TB_sceneOpened.js
- avalon/harmony/lib.py
> Harmony to 3.0 structure

- avalon/blender/ops.py
this is the same fix as #284 for Pype 3
> Blender: fix #284

- avalon/harmony/TB_sceneOpened.js
Requires:
https://github.com/pypeclub/pype/pull/1266
Fixes location of workfiles
> Fix Openpype harmony deadline

- avalon/tvpaint/communication_server.py
- avalon/tvpaint/plugin_code/CMakeLists.txt
Forwards compatibility PR.
- renamed TVPaint plugin .dll file to `OpenPypePlugin`
- changed project name of C++ code to `OpenPypePlugin`
- added new operation to remove previous plugin if is in plugins folder
||Pype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/311|
> Rename TVPaint plugin

- avalon/harmony/TB_sceneOpened.js
- avalon/harmony/__init__.py
- avalon/harmony/js/AvalonHarmony.js
- avalon/harmony/lib.py
- avalon/harmony/pipeline.py
2.x version of pypeclub/avalon-core#302
> Harmony - add SubsetManager to menu

- avalon/api.py
- avalon/pipeline.py
This is port of #297 to openpype 3.0
> 3.0 cache discovered plugins

- avalon/tools/lib.py
- avalon/tools/loader/lib.py
- avalon/tools/loader/model.py
- avalon/tools/loader/widgets.py
- avalon/tools/sceneinventory/app.py
- avalon/tools/sceneinventory/model.py
Closes https://github.com/pypeclub/pype/issues/1335 and https://github.com/pypeclub/OpenPype/issues/1337
> Fix wrong calculation of group availability

- avalon/tools/libraryloader/app.py
- avalon/tools/loader/model.py
- avalon/tools/loader/widgets.py
Added same implementation as in Loader
Requires:
https://github.com/pypeclub/OpenPype/pull/1475
> Feature Sync server in library loader

- avalon/blender/ops.py
- add return value to publish operation on execute
||OpenPype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/328|
> Blender publish ops return value

- avalon/tools/lib.py
- avalon/tools/libraryloader/app.py
- avalon/tools/loader/lib.py
- avalon/tools/loader/model.py
- avalon/tools/loader/widgets.py
Clicking on asset from sync disabled project resulted in error.
Fixed menu actions
Fixed change project event on RepresentationModel
> Fix Sync server in library when disabled

- avalon/tools/loader/widgets.py
2.x version of https://github.com/pypeclub/avalon-core/pull/339
Requires:https://github.com/pypeclub/OpenPype/pull/1549
> Delivery in LibraryLoader - add version documents to items

- avalon/tools/loader/widgets.py
Requires:
https://github.com/pypeclub/OpenPype/pull/1546
> Delivery in LibraryLoader - added version document to Subset list

- avalon/pipeline.py
- avalon/tools/loader/lib.py
- avalon/tools/loader/widgets.py
Closes https://github.com/pypeclub/client/issues/46
Requires: https://github.com/pypeclub/OpenPype/pull/1726
> PS - added loader from sequence

- avalon/tools/lib.py
- preparation for dynamic openpype modules
- moved import of sync server to function where it's used and add backwards compatibility in it
- this is backwards compatible so it can be merged before related PR
||Relates to PR|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1872|
> Dynamic OpenPype modules

- avalon/toonboom/avalon.js
- fix workfiles import in toonboom .js
> ToonBoom: Workfiles import fix

- avalon/aftereffects/lib.py
- avalon/blender/ops.py
- avalon/harmony/TB_sceneOpened.js
- avalon/maya/pipeline.py
- avalon/nuke/pipeline.py
- avalon/photoshop/lib.py
- avalon/toonboom/avalon.js
- avalon/tvpaint/communication_server.py
- avalon/unreal/pipeline.py
- use loader and library loader from openpype tools
| | Related PRs|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/2038|
> Loader & Library loader: Use tools from OpenPype

- avalon/tvpaint/communication_server.py
- avalon/tvpaint/plugin_code/library.cpp
- modified TVPaint plugin to be able change menu items in TVPaint based on send data from python
- added experimental tools callback
> TVPaint: Add experimental tools

- avalon/photoshop/lib.py
Requires: https://github.com/pypeclub/OpenPype/pull/2246
> Remove IS_HEADLESS env var in PS webpublishing

- avalon/aftereffects/pipeline.py
- avalon/harmony/pipeline.py
- avalon/photoshop/pipeline.py
Closes [#2333](https://github.com/pypeclub/OpenPype/issues/2333)
How to test:
-------------
- load something via Load into workfile
- Publish
- without this PR it would fail in `Collect Versions Loaded in Scene`
> Fix loaded containers object name issue

- avalon/unreal/__init__.py
- avalon/unreal/pipeline.py
Unreal also should have access to experimental tools.
- add function callback which will show experimental dialog
> Unreal: Add function for showing experimental button

- avalon/pipeline.py
Bugfix when switching task in workfile interface.
> Add task type task short in

- avalon/pipeline.py
blocking https://github.com/pypeclub/OpenPype/pull/2630
> adding studio name and code to anatomy data

- avalon/api.py
- avalon/pipeline.py
Move "Create workflow" from avalon-core into OpenPype.
- removed logic connected to create workflow
Depends on https://github.com/pypeclub/OpenPype/pull/2854
> General: Move create logic from avalon to OpenPype

- avalon/schema.py
Schemas are cached on import which may cause issues if env `AVALON_SCHEMA` is not set yet.
- cache schemas on first usage of `validate` function
> Schema: Do not cache on import
