avalon/pipeline.py

hierarchy is set to empty string if no parents

hierarchy is set to empty string if no parents

---

avalon/nuke/lib.py
avalon/nuke/pipeline.py

Improving the way Set Frame Range works in Avalon menu.
- it will set frame range for the script
- it will define handles in active viewer frame range slider

feat(nuke): cleaning nuke.lib prints, adding active viewer frame ranges

---

avalon/tools/workfiles/app.py

- listdir is alphabetically reversed so higher version is first

listdir is alphabetically reversed so higher version is first

---

avalon/tools/workfiles/app.py

This prevents Nuke from opening the workfile script in another window > faster loading.

Open script in same window

---

avalon/pipeline.py

- workdir is created when update_current_task is called (on accept button in context manager)

PYPE-459_workdir_not_created

---

avalon/tools/gui/widgets/widget_assets.py

select_assets expect list or tuple but single item is feeded as str. Therefor switching context doesn't work. String is converted to list and all is ok.

select_assets expect list or tuple

---

avalon/pipeline.py

- added easy check if filename has `#` or `%` then will try to find in files at same directory if any matches same start of filename and extension
- `seq01_sh00030_plateMain_v001.####.exr` will be split by "#" and checked if exist file which start with "seq01_sh00030_plateMain_v001." and ends with ".exr" (similar for `seq01_sh00030_plateMain_v001.%04d.exr`)

naive check of sequences in filename during path_from_data

---

avalon/nuke/lib.py

- also it was unnecessary to use list prefix in set avalon knob data

nuke avalon knobs were spreding to all write/read nodes

---

avalon/maya/commands.py

- `reset_frame_range` updated with handles
- removed try except (it was impossible to raise KeyError there)
- renamed `shot` variables to `asset`
- fps is set first since does not require asset entity

Feature/pype-725 #close maya frame range

---

avalon/tools/loader/model.py

Curently the Hound keeps leaving the same "files could not be reviewed" comments in getavalon/core#535, so I removed the function calls in argument defaults as what it demanded.

No function calls in argument defaults

---

avalon/nuke/workio.py

Since we clear the current script and read in contents of the file path instead of loading the script (to stay within the same window), there are no callbacks emitted by Nuke. To accommodate callbacks on loading we introduce this signal.

Emit signal when opening a file through workfiles app.

---

avalon/lib.py

This PR requires pype https://github.com/pypeclub/pype/pull/169 and pype-config: https://github.com/pypeclub/pype-config/pull/27.
Issue:
New structure of pype requires to import modules from `hosts` subfolder in avalon's config installation.
Solution:
Avalon config import was modified to be check `{config}.hosts.{host_name}` first

3.0/feature/pype refactor start

---

avalon/harmony/lib.py

Non-threaded saving because threading is not safe.

Fix scene_save

---

avalon/harmony/server.py

sometimes when using `send()` function on Python side result was returned faster then `send()` could block and wait. This resulted in unprocessed replies from Harmony.
This fix is storing every recieved request in queue. `send()` is then looking there for it. It is removed after being processed.

Harmony: fix race condition in server

---

avalon/harmony/__init__.py
avalon/harmony/lib.py
avalon/harmony/pipeline.py

Metadata for each container is stored on the scene level, instead of on nodes only.
This enables the Harmony implementation to containerize other objects than nodes.
This does break backwards compatibility, but the production data using this is minimal.

Scene Metadata

---

avalon/harmony/lib.py
avalon/tools/workfiles/app.py

Sometimes zip coming from Mac can contain files with invalid characters for Windows platform. We found case with `Icon\r` file but potentially there can be many more. Python's **zipfile** module already has basic checks against `:<>|"?*` but is missing `\r`.
Extend **zipfile** mechanism with other characters, This is done by subclassing `zipfile.ZipFile` and overriding `_windows_illegal_name_trans_table` defined there that is used to translate illegal characters to `_`.
Added archive verification after zip is created and before it is moved to final destination.

Harmony: handle invalid characters in zips

---

avalon/harmony/server.py

Sometimes operations in Harmony can take too long and 2 minutes were not enough for heavy scenes. This increases timeout to 15 minutes.

Harmony: Increase timeout to 30 minutes

---

avalon/pipeline.py

Fix for error when running actions;
```
Traceback (most recent call last):
File "C:\Users\admin\bumpybox_development\pype-setup\repos\avalon-core\avalon\tools\libraryloader\widgets.py", line 334, in on_context_menu
representation=representation
File "C:\Users\admin\bumpybox_development\pype-setup\repos\avalon-core\avalon\tools\libraryloader\lib.py", line 294, in load
loader = Loader(context)
File "C:\Users\admin\bumpybox_development\pype-setup\repos\avalon-core\avalon\pipeline.py", line 193, in __init__
if project_doc and project_doc["name"] != Session["AVALON_PROJECT"]:
KeyError: 'AVALON_PROJECT'
```

Loader actions fix.

---

avalon/harmony/lib.py

Current implementation requires *xstage* file named as workfile zip itself. This doesn't work if artist save scene under different name. In such case there is the error "Scene cannot be found". 
This PR is walking through workfile zip, finding all xstage file. There should be only one, but in case there are more, it will prefer the one with the zip file name, otherwise first one it finds.
Closes: pypeclub/pype#526

Harmony: make xstage files independent on zip name

---

avalon/harmony/README.md
avalon/harmony/TB_sceneOpened.js
avalon/harmony/lib.py
avalon/harmony/pipeline.py
avalon/toonboom/lib.py

`func` is already existing object in Harmony namespace. We use `func()` for functions we send from server to Harmony client. When they are eval()ed there, they replace Harmony object making some Hamony functions as *Create keys...*  unusable.
Added random **uuid4** prefix for all generated functions by Pype and Avalon core to minimaze possible clash.
🏴 **Relates to similar PR in:** pypeclub/pype#584
|---|

Harmony: fix clashing namespace in js function calls

---

avalon/harmony/lib.py

Empty scene in Harmony is realized by copying and extracting `temp.zip` to `~/.avalon/harmony`. This is never cleared as it is using the same mechanism as with other shots - it is removed and extracted again only if `temp.zip` is newer then extracted directory and that rarely (almost never) happens.
If user doesn't immedietly save empty scene under other name, it will get contaminated with different kinds of things, palettes, audio, etc. This will then persist between all empty scene started later.
##Solution
forcefully removing `~/.avalon/harmony/temp` whenever blank scene is opened.
Fix pypeclub/pype#583

Harmony: clear temp scene before opening

---

avalon/harmony/TB_sceneOpened.js

Fixing race-condition when we are emitting signal `application.launched` possibly before we are connected to socket. This will trigger communication that won't really happen because socket is not ready yet. Result is blocked client-server communication.

Harmony: emit signal only after connected to socket

---

avalon/tools/libraryloader/widgets.py
avalon/tools/loader/widgets.py

- currently loader just crash if loading crash which may cause and issue if we are not in maya or nuke
- exceptions are caught and details about crash are shown in popup message box

Loader catch load fail and show details

---

avalon/harmony/TB_sceneOpened.js

Sometimes there was race condition when communicating with server. If one process has not finished and user tried to open *Loader* for example, server would still expecting result from previous action but got request for opening Avalon tool instead.
This adds locks, so when Harmony is processing something, it will create lock for communication with server. All calls sending request to server will wait until lock is removed.
**Note:** I couldn't test it properly as that race condition never happend on my setup.
🎫 **ticket ID:** [#235](https://support.pype.club/a/tickets/245)
|---|

Harmony: add locks to prevent concurrent communication with server

---

avalon/harmony/TB_sceneOpened.js

in some casis `received` buffer could be cleared by `send()` function during receiving incoming request from server. In that case `JSON.parse(received)` could break.
Added docstrings and made code more compact

Harmony: fix for buffer clearing

---

avalon/harmony/TB_sceneOpened.js

Automatic call to `pype.hosts.harmony.ensure_scene_settings()` resulted in communication problems between client <-> server.
Similar PR to pypeclub/pype#637 is disabling this functionality in Pype, this PR is promoting separate function to be added to Harmony toolbar to allow user for manuall call.
🏴 **dependes on:** pypeclub/pype#637
|---|

Harmony: Disable auto setting of scene

---

avalon/vendor/qargparse.py

- Few Qt bindings do not support checkState on `QPushButton` (`checkState` & `setCheckState` methods)
- For these bindings was added check if widget has attribute `isChecked` in that case are used methods: `isChecked` and `setChecked`
- added icon to reset button so user can imagine why is there

QArgparse fix of toggleable button

---

avalon/tools/lib.py

- `qtawesome` module is used in import stage which cause crash if QtApplication is not running yet
- `qtawesome` module must render images in running Qt application but that is not happening if application is not running yet and tools are imported
- default icons are not created in import stage but on first demand

Stop use Qt in import stage

---

avalon/tools/libraryloader/app.py
avalon/tools/models.py

- asset model can have running multiple threads fetching asset documents which is inefficient and cause duplicated items in asset view
- fetch is skipped if fetch thread is already running
- library loader has to stop fetch manually on project change as running fetch thread may be still running but for different project

Avoid multiple asset fetch

---

avalon/tools/models.py
avalon/tools/widgets.py

- previous fix did it's job but worked only on very fast queries, which is not ideal (https://github.com/pypeclub/avalon-core/pull/221)
- refresh of assets is not possible if attribute `_doc_fetching_thread` is not set to `None`
- this requires to set `_doc_fetching_thread` to `None` after all processing which is handled
- do not fill any items to model if fetching was stopped
|---|---|
|pype|https://github.com/pypeclub/pype/pull/726|

Asset fetch second fix

---

avalon/pipeline.py
avalon/tvpaint/communication_server.py
avalon/tvpaint/lib.py
avalon/tvpaint/pipeline.py

- class `Loader` has new method `filepath_from_context` which does what was in `__init__` of Loader but this way is accessible and usable anytime in loader object
- moved plugin copy before websocket server has started so opened python process won't get stuck on error
- remove temporary file with workfile metadata
- temporary files has prefix now
|---|---|
|pype|https://github.com/pypeclub/pype/pull/752|

TVPaint update fix

---

avalon/style/style.qss

Current stylesheets set font size in pixels which is not scaled properly if Qt autoscaling is not working on 4k resolution. But is scaled properly when set in points (specifically in Maya).
- changed global font size in style from `12px` to `9pt` and from `11px` to `8pt` in one specific object name

Font size in points

---

avalon/tvpaint/__init__.py
avalon/tvpaint/pipeline.py
avalon/tvpaint/workio.py

It is possible to have opened multiple workfiles at the same time from different contexts. Which is not an issue for most of avalon workflow but is issue for publishing.
Each workfile contain metadata with `"project"`, `"asset"` and `"task"` to keep context in which were workfiles created.
|---|---|
|pype|https://github.com/pypeclub/pype/pull/766|

TVPaint store context to workfile metadata (764)

---

avalon/tvpaint/pipeline.py

- store layer ids to `"members"` keys instead of `"objectName"`
- kept backwards compatibility if `layer_ids_from_container` method is used to get layer ids from container
|---|---|
|pype|https://github.com/pypeclub/pype/pull/769|

TVPaint store members key

---

avalon/tools/libraryloader/app.py

This removes presets from library loader. It was used to pick default library, however the it introduced pype dependency to core, for very little benefit

remove presets from library loader

---

avalon/tools/creator/app.py

no change in behaviou, just moving presets to settings for automatically selecting the correct family in creator based on task

use settings in creator instead of presets

---

avalon/api.py
avalon/pipeline.py
avalon/tools/libraryloader/app.py
avalon/tools/libraryloader/lib.py
avalon/tools/workfiles/app.py

Pype config logic has been moved to settings and resolved in pre-hooks, so we no longer need this dependency in avalon

remove pype presest from workfiles launching

---

avalon/mongodb.py
avalon/pipeline.py

PR does not remove hierarchy concept just skip handling of `AVALON_HIERARCHY` key in environments and `Session`.
- removed `AVALON_HIERARCHY` from session keys
- where `AVALON_HIERARCHY` was set (on context change) is not anymore
- usage of `AVALON_HIERARCHY` was replaced with querying asset document and compute the hierarchy from `data.parents` value
- this is how it was done on context change so it is not backwards compatible breaking just removed dependency of one key
- in `_format_work_template` function is used `template_data_from_session` to get fill data so there is only one place where these data are collected

Remove AVALON_HIERARCHY

---

avalon/tools/loader/widgets.py

- Loader may crash on `load` exception catch because is using variable `representation` which may be None at the time.
- Instead of using `representation["name"]` is used variable `representation_name` which is always filled at the time

Fix variable in loader exception catch

---

avalon/vendor/qtawesome/__init__.py
avalon/vendor/qtawesome/iconic_font.py

- fonts from qtawesome module are not reset if QApplication was recreated
- qtawesome module has check for font ids in `QtGui.QFontDatabase` and reload fonts if they are not available

Awesome font reload fix

---

avalon/vendor/qtawesome/__init__.py
avalon/vendor/qtawesome/iconic_font.py

- fonts from qtawesome module are not reset if QApplication was recreated
- qtawesome module has check for font ids in `QtGui.QFontDatabase` and reload fonts if they are not available

Awesome font reload fix 2

---

avalon/tvpaint/pipeline.py

- split get_workfile_metadata into 2 parts one only read string and second do json serialization
|---|---|
|pype|https://github.com/pypeclub/pype/pull/809|

TVPaint repair invalid metadata

---

avalon/harmony/TB_sceneOpened.js

Fixing not working `ensure scene settings` function in Harmony. See #802
🏴 **Relates to:** pypeclub/pype#806
|---|
close pypeclub/pype#802

Harmony: fix `ensure scene settings` function

---

avalon/tvpaint/pipeline.py

Seems like TVPaint's workfile metadata have strictly limited metadata string length limitation in specific versions of TVPaint. This cause that stored metadata are lost.
Store metadata value by string chunks. With this is possible to add unlimited length of metadata string (in theory).
**Current data in workfile:**
```
[avalon]
instances=[{..data string..}]
```
**New way of storing data:**
```
[avalon]
instances=3
instances0=[{...start of data string...
instances1=...some more data...
instances2=...end of data string}]
```
This ways was kept backwards compatibility of loading metadata values as it is just check if value contain only numbers.
Added auto-fix of invalid metadata values. They are not usable anyway.
- loading of metadata is a little bit slower as it has to ask TVPaint twice …

TVPaint store metadata by chunks

---

avalon/tvpaint/workio.py

Same issue as PR in pype https://github.com/pypeclub/pype/pull/886 did. Used path with spaces must be wrapped with quotes and double quotes. Strange is that save of workfile do not require this wrapping.
Path to workfile is wrapped in format `'"'"{}"'"'` so workfiles with spaces in paths can be opened.

TVPaint load workfile path with spaces

---

avalon/tools/libraryloader/app.py
avalon/tools/widgets.py

- Library Loader is refreshed on initialization which slows down tray initialization
- Library loader is not refreshed on initialization but refresh must be called
- removed unused metho `on_refresh_clicked`
- refresh button is not stored to `refreshButton` in asset widget as is not used in code
|:black_flag:|Pype 2.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/254|

Explicit library loader refresh

---

avalon/tvpaint/pipeline.py

- it was found out that layer ids are not workfile related so they can't be used as unique identifier across all workstations
- `containerise` is not specific about `layer_ids` but use `members` argument instead
- renamed `layer_ids_from_container` to `get_members_from_container`
|---|---|
|pype|https://github.com/pypeclub/pype/pull/903|

TVPaint without layer ids

---

avalon/pipeline.py
avalon/schema.py
avalon/tools/delegates.py
avalon/tools/loader/model.py
avalon/tools/sceneinventory/app.py

There were found out several issues with master version implementation.
1.) Master version documents queried from mongo didn't have enough data to be painted properly in subset view (loader).
2.) Master versions were not handled in `get_repres_contexts`.
3.) Action in scene inventory `Switch to versioned` don't work because of bad variable usage
4.) During fixing of issue 1.) was discovered that the issue is happening because the schema check on subset is not 100% in pype's modifications.
- version delegate have access to all required data for master versions
- `get_repres_contexts` collect required data for master versions
- fixed `Switch to versioned` action in Scene inventory tool
- schema check was modified to care only about version of the schema not for whole string
- implemented …

Master versions fix

---

avalon/harmony/lib.py

Removed unneeded workaround. Pyblish is not running exec_ anymore.
Requires:
pypeclub/pype#911

Harmony deadline submission

---

avalon/schema.py

- `get_schema_version` return integeres, not strings
|:black_flag:|Pype 2.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/268|

Fix schema version extraction

---

avalon/tools/sceneinventory/app.py

- sometimes it is necessary to quickly set asset in switch dialog to current context asset (Based on PR https://github.com/pypeclub/avalon-core/pull/215)
- added button which set current context asset in asset box on click
|:black_flag:|Pype 3.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/271|

Set current asset in switcher with button

---

avalon/photoshop/lib.py

Safer way to launching PS with workfile. Without this some characters in workfile path could be consumed. This handles escaping better.
|:black_flag: |Pype 2.x PR|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/274

Photoshop safer loading workfile

---

avalon/tools/loader/model.py

- integrated subset document may not have filled `families` keys
- used `None` family if families are empty
|:black_flag: |Pype 2.x PR|
|---|---|
|pype|https://github.com/pypeclub/avalon-core/pull/278|

Fix missing families on subset

---

avalon/harmony/TB_sceneOpened.js

Without it $ wont be available for pype js plugins
Requires:
pypeclub/pype#981

2.x/Harmony - fix - add loading of openHarmony.js when creating menu

---

avalon/pipeline.py
avalon/tools/loader/model.py

- pype didn't publish families into subset so schema version check does not work for subsets published before 2.15.0
- loader's subset model does not count on missing versions for subset
- added Pype specific backwards compatibility into `is_compatible_loader` to use families from both subset and version
- subsets without version are not showed in loader gui

Use families from both subset and version for loader filtering

---

avalon/blender/ops.py
avalon/pipeline.py
avalon/tools/loader/model.py

This is fixing bug when Avalon windows opened in Blender on Centos Linux (at least?) didn't processed events and were "frozen".

Blender: make tool windows work on linux again

---

avalon/maya/commands.py

This adds ability to reset resolution in Maya for Vray. All other renderers store resolution in `defaultResolution.width`, but not vray. No. Vray stores it in its own attribute `vraySettings.width`

Maya: fix reset resolution for Vray

---

avalon/pipeline.py
avalon/tools/creator/app.py
avalon/tools/models.py

- subset template for creator api is defined by `Creator` class with class method `get_subset_name`
- the method by default returns what was hardcoded in Creator tool
- modified how duplicated subset names are checked and already existing subset values are prepared
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1072|
|pype-config|https://github.com/pypeclub/pype-config/pull/101|
|:black_flag: |Pype 3.x PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1068|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/288|

Optionally add task to subset name

---

avalon/tvpaint/communication_server.py
avalon/tvpaint/lib.py

- implemented lib method to collect pre/post behavior of passed layer ids
- remove QuickTime path from PATH environment variable
- this can break loading of images or videos to TVPaint
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1084|
|:black_flag: |Pype 2.x PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1080|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/292|

TVPaint extractor enhancement

---

avalon/tools/loader/app.py

Refresh selection in loader on context change (change of task or asset in workfiles tool).
- added callback in loader tool to change asset on avalon's "taskChanged" event which is triggeret by Workfile tool on context change
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1106|
|:black_flag: |Pype 3.x PR|
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1107|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/299|

Reset loader's asset selection on context change

---

avalon/tvpaint/communication_server.py

TVPaint's implementation is using `win32com.shell` which is not available in build.
- it was found out that the module `win32com.shell` actually is `win32comext.shell` which is available in build so just changed source of import
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1182|

Fix TVPaints usage of pywin

---

avalon/aftereffects/lib.py
avalon/blender/ops.py
avalon/harmony/TB_sceneOpened.js
avalon/harmony/lib.py
avalon/photoshop/lib.py
avalon/toonboom/avalon.js
avalon/toonboom/lib.py
avalon/tvpaint/communication_server.py
res/houdini/MainMenuCommon.XML

Avalon's workfiles tool may not work properly in Pype 3 as there were needed some changes. To be able change usage of workfiles tools in most of hosts requires to change imports inside their implementation which is in avalon module.
Pype's workfile tool is currently used only in nuke or maya. This is change is for remaining hosts.
- changed imports of workfile tool in avalon's host implementation

Pype workfiles tool in all hosts

---

avalon/pipeline.py

Forwards compatible changes for Pype 3.
- tools are split by slash `"/"` before loading of tool's environments
- this is because tools are stored with slash in Pype 3 where separate tool's group name and tool's variant name (See in [PR](https://github.com/pypeclub/pype/pull/1190) )
|---|---|
|pype|https://github.com/pypeclub/pype/pull/1197|
|pype-config|https://github.com/pypeclub/pype-config/pull/105|

Forwards compatible config

---

avalon/tvpaint/communication_server.py
avalon/tvpaint/plugin_code/CMakeLists.txt

- renamed TVPaint plugin .dll file to `OpenPypePlugin`
- changed project name of C++ code to `OpenPypePlugin`
- added new operation to remove previous plugin if is in plugins folder
- this may break Pype 2/Pype 3 as `AvalonPlugin.dll` is removed when TVPaint is launched from Pype 3 but `OpenPypePlugin.dll` for this purposes was made a forwards compatible PR into Pype 2
||Pype 2 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/312|

Rename TVPaint plugin

---

avalon/tvpaint/lib.py

- return output of `groups_data` function in TVPaint's lib is missing
- return output of `groups_data` function
||Pype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/315|

Fix TVPaint groups_data function

---

avalon/api.py
avalon/pipeline.py

**Goal**
To cache plugins for later use.
**Motivation**
There is currently no way of getting already registered plugins without running `api.discover`. When doing this inside a plugin it results in that instance of the plugin getting flushed from memory. An example of this:
```python
from avalon import api, io
class ProjectionLoader(api.Loader):
"""
This will load camera, pointcache and image to build a projection setup.
"""
families = ["projection"]
representations = ["json"]
label = "Load Projection"
icon = "camera"
color = "orange"
node_color = "0x3469ffff"
def load(self, context, name, namespace, data):
api.discover(api.Loader)
print(io.find_one({"_id": context["asset"]["_id"]}))
```
**Implementation**
Currently the cached plugins from the last `api.discover` call is stored under …

Cache plugins.

---

avalon/tools/loader/app.py
avalon/tools/loader/model.py
avalon/tools/loader/widgets.py

Tweaked visibility of columns required only when SyncServer is enabled.
Fixed '$first' unavailability in MongoDB < 4.4

Fix sync server visibility not enabled

---

avalon/tools/sceneinventory/app.py

- values in Swtich Asset UI are populated to comboboxes in random order which is confusing
- pass values to comboboxes sorted
||OpenPype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/323|

Sorted values in Switch Asset tool

---

avalon/blender/ops.py
avalon/blender/workio.py

QApplication should know about vibile and not visible windows to know if should process events or not. Publish UI is not stored to known opened windows so can't determine if should paint and execute logic. This happens only on specific versions of blender and on linux.
- pyblish gui is used directly from Pype
- Qt application processing of events is executed only on linux
||OpenPype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/320|

Blender Publish GUI execution

---

avalon/pipeline.py

- all formatted paths in `get_representation_path` are forced to replace `\` with `/` on all systems except windows
- this is because `os.path.normpath` may not replace it automatically and MacOS can't handle it automatically
- don't use `hierarchy` key from asset document but use joined `parents` key
Resolves: https://github.com/pypeclub/OpenPype/issues/1411

Wrong handling of slashes when loading on Mac

---

avalon/tools/loader/model.py

Change of version in LibraryLoader and Loader resulted in runtime exception if Sync Server wasn't enabled.

Fix failure in LibraryLoader if no Sync Server

---

avalon/api.py
avalon/pipeline.py
avalon/tools/libraryloader/app.py
avalon/tools/loader/lib.py
avalon/tools/loader/widgets.py

OpenPype 3 version of [PR](https://github.com/pypeclub/avalon-core/pull/329)
- SubsetLoader only appears once in the right click menu.
- If a SubsetLoader support multiple contexts with `is_multiple_context_compatible` attribute, it'll get a list of contexts passed to its `load` method.
- partially fixed `RepresentationWidget` in library loader
- `AvalonMongoDB` was not passed to widget and widget internally used `avalon.io`
- added filtering of `SubsetLoader` inside `RepresentationWidget`
||Pype 2 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/329|
|pype|https://github.com/pypeclub/OpenPype/pull/1484|
||Relates to PRs|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1497|

SubsetLoader and support multiple contexts

---

avalon/blender/pipeline.py
avalon/blender/workio.py

Callbacks on "open file" must be decorated with blender decorator to be able trigger it which was not used for callback which should reenable processing of Qt events.
- callback is triggered with global blender implementation callback `_on_load_post` instead of separated method
- this issue happens on linux where Qt event can't be processed during workfile loading
||OpenPype 3 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/338|

Blender post load callback fix

---

avalon/harmony/lib.py
avalon/harmony/pipeline.py

Closes: https://github.com/pypeclub/OpenPype/issues/1191
SubsetManager cleans all instances which haven't matching write node in scene anytime is opened.
Publish is handled already as its looping through physical nodes, not metadata.
To test:
> Create instance
> Check that shows up in SubsetManager
> Delete created write node for a instance
> Check that instance is not showing in SubsetManager (and it isnt in Window>Metadata Editor)

Feature #1191 subset manager shows deleted harmony

---

avalon/tools/lib.py
avalon/tools/libraryloader/app.py
avalon/tools/loader/app.py
avalon/tools/loader/widgets.py
avalon/tools/widgets.py
avalon/tools/workfiles/app.py

- added Set current asset button to loader
- library loader won't refresh until refresh is triggered by method or window is shown
- library loader has `< Select project >` item and projects are sorted by name
||Related to PRs|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1623|
Closes: https://github.com/pypeclub/OpenPype/issues/1448
Closes: https://github.com/pypeclub/OpenPype/issues/1603

Loader and Library loader enhancements

---

avalon/tools/libraryloader/app.py
avalon/tools/loader/model.py
avalon/tools/models.py
avalon/tools/widgets.py

- project change in library loader may cause a crash - this happens when project is set to None or when project refresh happens
```
Traceback (most WARNING:pyblish.plugin:Path already registered: C:\openpype\OpenPype\openpype\plugins\publish
recent call last):
FilFetching asset..
e "C:\openpype\OpenPype\repos\avalon-core\avalon\tools\lib.py", line 557, in run
func(*args, **kwargs)
File "C:\openpype\OpenPype\repos\avalon-core\avalon\tools\loader\model.py", line 336, in _fetch
asset_docs = self.dbcon.find(
File "C:\openpype\OpenPype\repos\avalon-core\avalon\mongodb.py", line 307, in __getattr__
self._database[self.active_project()],
File "C:\openpype\OpenPype\.venv\lib\site-packages\pymongo\database.py", line 300, in __getitem__
return Collection(self, name)
File …
```

Library loader refresh fix

---

avalon/tools/creator/app.py

Customizable subset template may currently break TVPaint `renderPass` and `renderLayer` families as their subset names are based on expectation of original template and the template is not used at the end. Because of that it is required to store user's input (variant) into instance data to be able handle that data afterwards.
- store variant to data of instance data when creation is executed from creator tool
- enable curly brackets in subset name before executing "create" as it may identify unfilled dynamic keys that will be filled on creation
- raised `CreatorError` shows dialog
||Related to PRs|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/1662|

TVPaint custom subset template

---

avalon/pipeline.py

- template in representation may be stored with backslashes when published from windows which cause not working paths on linux and mac on load
- replace backslashes with forward slasesh on linux and mac
Issue for OpenPype 3 was fixed with https://github.com/pypeclub/avalon-core/pull/324/files

Slash in paths fix

---

avalon/io.py

Import cycle was breaking Avalon core initialization in Pype 2.x

Houdini: Import error in 2.x

---

avalon/aftereffects/lib.py
avalon/photoshop/lib.py
avalon/tools/webserver/app.py

For cases that app is already running, but same app is triggered again from launcher or FTrack to save booting time
Requires:
https://github.com/pypeclub/OpenPype/pull/1811
How to test:
-------------
Open PS via Ftrack (or launcher) from one asset
Keep PS open
Try to open PS via FTrack (or launcher) from different asset
- it should log that is sending context change, original PS is kept open, context should be changed (check after publish if representation were added to correct asset)
For PS it doesn't solve an issue that artist would switch between multiple opened workfiles. (AE doesn't allow that.)
Validator was added for PS to compare expected context with current, artist is informed and can decide to fix (replace) context, or reopen workfile via Workfiles app to refresh context.

PS, AE - send actual context when another webserver is running

---

avalon/aftereffects/lib.py
avalon/harmony/lib.py
avalon/photoshop/lib.py

Photoshop does not launch on MacOS when stdout is set to subprocess.PIPE and stderr is not defined
- probably because does not have permissions to use it or can't use it
- redirect stdout and stderr of adobe apps to devnull on launch

Adobe apps stdout/stderr definition

---

avalon/pipeline.py
avalon/tools/loader/lib.py

Now is options dialog during loadin shown all the time if options are available.
- options dialog is shown only if was clicked on option subbutton
- have published representation that has loader with options
1. open host
2. load the representation without and with options and check if are loaded as expected

Loader options fix

---

avalon/mongodb.py

Conditions in autoinstall are not working as expected and autoinstall does not work at all. Also `__getattr__` raises strange errors if something is not right.
- autoinstall does work as expected
- when project is not set `ValueError` is raised
- when method is not available on collection `AttributeError` is raised
- `projects` method has ability to specify query filter and projection of documents
- environment `AVALON_DB` is converted to `str` as it may be `unicode` in python 2 hosts
**Autoinstall**
- run this (e.g. in host)
```
from avalon.api import AvalonMongoDB
project_name = "Your project name"
dbcon = AvalonMongoDB()
dbcon.Session["AVALON_PROJECT"] = project_name 
project_doc = dbcon.find_one({"type": "project"})
dbcon = AvalonMongoDB(auto_install=False) …
```

AvalonMongoDB auto install

---

avalon/io.py

Import cycle was breaking Avalon core initialization in Pype 2.x
Don't use api import in `io.py` to not cause circular import.
||OpenPype 2 PRs|
|---|---|
|avalon-core|https://github.com/pypeclub/avalon-core/pull/351|

Houdini: Import error in 3.x

---

avalon/tools/lib.py

- scene manager is crashing when contain loaded representations created with pype 2
- `get_progress_for_repre` does not crash with representations from pype 2

Scene Manager: Pype 2 compatibility

---

avalon/api.py
avalon/pipeline.py

- `compute_session_changes` expect template key which will be used to get workdir path
||Depends on|
|---|---|
|openpype|https://github.com/pypeclub/OpenPype/pull/1966|

Workfiles: Support more workfile templates

---

avalon/pipeline.py

When returning the last workfile we need to normalize the path. Hosts like TVPaint have issues with non-normalized paths.

Normalize last workfile path.

---

avalon/maya/pipeline.py

Creates issues when running 'run_tests.ps1'
Requires: https://github.com/pypeclub/OpenPype/pull/1810

Removed orphaned import of mayalookassigner

---

avalon/tools/loader/app.py
avalon/tools/loader/model.py
avalon/tools/loader/widgets.py

- families listed in family widget contain only main families (first family in subset `data.families`)
- filtering of subsets works as expected when families are checked/unchecked in family widget

Loader: Families filtering

---

avalon/mongodb.py
avalon/tools/libraryloader/app.py

* The `AvalonMongoDB` object can now omit projects that has `data.active` field value set to `false` (consider project is active if `data.active` field doesn't exists).
* The argument `query_filter` of `AvalonMongoDB.projects()` method is now deprecated.
Example usage :
```python
from avalon.api import AvalonMongoDB
dbcon = AvalonMongoDB()
active_projects = [doc['name'] for doc in dbcon.projects(only_active=True)]
```

Enable `AvalonMongoDB.projects()` filtering with 'data.active' field

---

avalon/mongodb.py

Since 30.9.2021 does not work cloud mongo connection correctly because of invalid ssl certificates on most of machines. It is issue mainly on Windows machines.
- `AvalonMongoConnection` is using `OpenPypeMongoConnection` logic in it
- simplifies mongo connection handling to single place
||PR depends on|
|---|---|
|OpenPype|https://github.com/pypeclub/OpenPype/pull/2095|

General: Cloud mongo ca certificate issue

---

avalon/tools/sceneinventory/app.py

Describe the bug
If multiple loaded hero version are selected in the scene manager inside maya and user tries to switch all of them to explicit equivalent versions. The change only happens for the first one selected
To Reproduce
1. load multiple models into scene
2. open scene manager and change all to hero version
3. select all again and try changing them to versioned

OP-1902 - fixed multiple switch to versioned

---

avalon/tvpaint/communication_server.py

- communicator is using `self.log` but the object does not have `log` attribute available
- replaced 'self.log' with global 'log'

TVPaint: Fox log variable

---

avalon/pipeline.py

- when is installed host implementation which is available only in openpype it is installing module named `openpype.hosts.<host name>.api` instad of `openpype.hosts.<host name>` which cause a lot of warnings in `find_submodule` function which may be terrifting.
- skip "api" host name and use splitted part before that

General: Skip "api" module name on finding host implementation

---

avalon/pipeline.py
avalon/style/style.qss
avalon/tools/sceneinventory/app.py

Add option to choose from different loaders in switch dialog.
- added function `get_loader_identifier` to extract loader identifier (name)
- switch function may expect loader which will be used for switching
- switch dialog changes
- new method to get representation ids for currently context (selected containers and combobox values)
- have option to show menu popup if there are multiple loaders that can be used for loading
- loaders must match for all representations retrieved from currentl context of dialog
- loaders must have `switch` method available
- loaders with attribute `is_utility` set to True are skipped
- first option of menu is to `Use origin loaders` which will use loaders from containers
- the menu is not available if there is only one available loader which is same as for …

SceneInventory: Choose loader in asset switcher

---

avalon/nuke/pipeline.py

- pass variable (pointer to window) into callback triggering showing tool instead of passing function callback

Rools: Parenting of tools in Nuke

---

avalon/pipeline.py

I added the parent key in template_data_from_session to solve the problem when changing tasks in the work file interface.
Link to [OpenPypeV3: Add key parent asset to path templating construction](https://github.com/pypeclub/OpenPype/pull/2186)

Add parent in template_data_from_session 

---

avalon/aftereffects/launch_logic.py
avalon/photoshop/launch_logic.py

If user uses extension in non docked version, closing of extension menu caused closing of host app.
How to test it:
---------------
- before fix detach extension menu to floating window, close this extension window
- do the same after fix is applied

Fix Adobe extension closing issue

---

avalon/harmony/TB_sceneOpened.js

Add experimental tools callback.
- added experimental tools button in harmony
- fixed duplicated `onManage` function

Harmony: Experimental tools callback

---

avalon/unreal/__init__.py
avalon/unreal/pipeline.py

Menu items are not defined by unreal plugin which may be complicated as plugin is compiled on project reation and then is not updated.
It is better to create menu dynamically in python and menu in Unreal will have only 2 action callbacks.
- one will show tools in a dialog which will stay until user close it
- second will show tools in popup which will close on loose of focus
- added `show_tools_dialog` and `show_tools_popup` using `tools_ui` from openpype's unreal
||Depends on|
|---|---|
|openpype|https://github.com/pypeclub/OpenPype/pull/2422|
|unreal-plugin|https://github.com/pypeclub/avalon-unreal-integration/pull/3|

Unreal: Dynamic menu created in Python

---

avalon/houdini/pipeline.py

Simple fix to avoid naming conflicts during `avalon.houdini.pipeline.containerise`.

Ensure unique name during renaming to avoid errors on naming conflicts

---

avalon/maya/lib.py

**What's changed?**
Minor fix for Python 3 compatibility of `lsattrs` function since `.iterkeys()` does not exist in Py3.

lsattrs: Fix Py3 compatibility for Maya 2022

---

avalon/houdini/pipeline.py

**What's changed?**
Houdini 19+ Python 3 `hou.Node` instances can't be compared with Python's `<` and thus `sorted()` fails by default.
To reproduce the error, before this PR:
1. open e.g. Houdini 19.0.455 with Python 3.
2. load a few models with the pipeline.
3. Run the following code:
```python
import avalon.api
host = avalon.api.registered_host()
list(host.ls())
```
The following error is generated:
```python
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "S:\openpype\OpenPype\repos\avalon-core\avalon\houdini\pipeline.py", line 202
, in ls
for container in sorted(containers):
TypeError: '<' not supported between instances of 'ObjNode' and 'ObjNode'
```
This PR resolves that issue and also works fine in older Houdini releases.
Without this PR loaded assets …

Fix ls() for Hou 19 with Py3
